<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * One application: an applicant's relationship with a single job posting.
 *
 * What a status means — whether the application is closed, and whether it puts
 * the candidate in the Candidate Pool for this application — comes from
 * config/applications.php, the single definition every part of the portal
 * reads. Nothing here, or anywhere else, keeps its own list of closed statuses.
 */
class Application extends Model
{
    protected $table = 'tblapp_applications';

    // open_posting_id is generated by the database from closed_at; writing it
    // is an error, so it can never be mass-assigned.
    protected $guarded = ['open_posting_id'];

    // Stored values. They are data: see config/applications.php.
    public const APPLIED = 'Applied';
    public const DOCUMENTS_COMPLETE = 'Documents Complete';
    public const WITHDRAWN = 'Withdrawn';
    public const NON_RESPONSIVE = 'Non-Responsive';
    public const NOT_SELECTED = 'Not Selected';

    protected $casts = [
        'applied_at' => 'datetime',
        'closed_at' => 'datetime',
    ];

    /* ---------------------------------------------------------------------
     * The status table
     * ------------------------------------------------------------------- */

    /**
     * What a status means, from config/applications.php, or null for a status
     * the table does not list. Matched the way the database compares the
     * column (case-insensitive), so PHP and SQL never disagree about a row.
     *
     * @return array{closed: bool, candidate_pool: bool}|null
     */
    public static function statusDefinition(?string $status): ?array
    {
        $statuses = config('applications.statuses', []);
        $status = trim((string) $status);

        if (isset($statuses[$status])) {
            return $statuses[$status];
        }

        foreach ($statuses as $key => $definition) {
            if (strcasecmp($key, $status) === 0) {
                return $definition;
            }
        }

        return null;
    }

    /** Stored values of every status that ends an application. */
    public static function closedStatuses(): array
    {
        return self::statusesWhere('closed');
    }

    /** Stored values of every status that retains the candidate for that application. */
    public static function candidatePoolStatuses(): array
    {
        return self::statusesWhere('candidate_pool');
    }

    private static function statusesWhere(string $flag): array
    {
        return array_keys(array_filter(
            config('applications.statuses', []),
            fn ($definition) => !empty($definition[$flag])
        ));
    }

    /** Ended. An unlisted status is treated as open. */
    public function getIsClosedAttribute(): bool
    {
        return (bool) (self::statusDefinition($this->status)['closed'] ?? false);
    }

    /**
     * In the Candidate Pool for THIS application. An applicant's other
     * applications are unaffected; there is no applicant-wide pool status.
     */
    public function getInCandidatePoolAttribute(): bool
    {
        return (bool) (self::statusDefinition($this->status)['candidate_pool'] ?? false);
    }

    /** The applicant-facing wording for the status (config applications.display). */
    public function getDisplayLabelAttribute(): string
    {
        return self::displayFor($this->status)['label'] ?? (string) $this->status;
    }

    /** The pill class for the status. An unlisted status looks like an open one. */
    public function getPillClassAttribute(): string
    {
        return self::displayFor($this->status)['pill'] ?? 'zn-pill-acc';
    }

    private static function displayFor(?string $status): ?array
    {
        foreach (config('applications.display', []) as $key => $display) {
            if (strcasecmp($key, trim((string) $status)) === 0) {
                return $display;
            }
        }

        return null;
    }

    public function scopeOpen($query)
    {
        return $query->whereNotIn('status', self::closedStatuses());
    }

    public function scopeClosed($query)
    {
        return $query->whereIn('status', self::closedStatuses());
    }

    public function scopeInCandidatePool($query)
    {
        return $query->whereIn('status', self::candidatePoolStatuses());
    }

    /* ---------------------------------------------------------------------
     * Relationships
     * ------------------------------------------------------------------- */

    public function applicant()
    {
        return $this->belongsTo(User::class, 'app_id', 'app_id');
    }

    /** Read-only pull of the linked job posting from zen-admin's portal_db. */
    public function jobPosting()
    {
        if (!$this->job_posting_id) {
            return null;
        }
        return DB::connection('zen')->table('tbl_job_posting')
            ->where('id', $this->job_posting_id)
            ->first();
    }

    /** Read-only pull of the linked manpower request position + parent MR No. from HireFlow. */
    public function requestPosition()
    {
        return DB::connection('hrd2')->table('tbl_manpower_request_position as p')
            ->leftJoin('tbl_manpower_request as r', 'r.id', '=', 'p.request_id')
            ->select('p.*', 'r.mr_no')
            ->where('p.id', $this->request_position_id)
            ->first();
    }
}