<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * One application's document gate (tblapp_document_processes): a deadline for
 * the requests HR attaches to it, and an outcome. HR starts it and changes it
 * in zen-admin; the applicant portal reads it.
 *
 * There is no attempt counter. The documents and requests belong to the
 * applicant and count for every application.
 */
class DocumentProcess extends Model
{
    protected $table = 'tblapp_document_processes';

    // active_application_id is generated by the database; it is never written.
    protected $guarded = ['id', 'active_application_id'];

    public const ACTIVE = 'active';
    public const COMPLETE = 'complete';
    public const NON_RESPONSIVE = 'non_responsive';
    public const WITHDRAWN = 'withdrawn';
    public const NOT_SELECTED = 'not_selected';

    protected $casts = [
        'deadline_at' => 'datetime',
        'started_at' => 'datetime',
        'outcome_at' => 'datetime',
        'deadline_days' => 'integer',
    ];

    public function application()
    {
        return $this->belongsTo(Application::class, 'application_id');
    }

    public function scopeActive($query)
    {
        return $query->where('status', self::ACTIVE);
    }

    public function getIsActiveAttribute(): bool
    {
        return $this->status === self::ACTIVE;
    }

    public function getStatusLabelAttribute(): string
    {
        return config('documents.completion.statuses.' . $this->status, $this->status);
    }

    /**
     * Calendar days from today to the deadline's date: 0 on the deadline day
     * itself ("due today"), never negative.
     *
     * Counted between the two DATES, not the two moments, so it is a whole
     * number in any Carbon version. (Carbon 3 in this app returns a fraction
     * from diffInDays between moments, Carbon 2 in zen-admin a whole number;
     * rounding those gave the applicant and HR different counts for the same
     * deadline.) zen-admin counts the same way.
     */
    public function getDaysLeftAttribute(): int
    {
        return max(0, (int) now()->startOfDay()->diffInDays($this->deadline_at->copy()->startOfDay(), false));
    }
}
